#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
#ifndef BASEUIELEMENTS_SWIFT_H
#define BASEUIELEMENTS_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BaseUIElements",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSCoder;

SWIFT_CLASS("_TtC14BaseUIElements17AlphaGradientView")
@interface AlphaGradientView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end

@class NSNumber;

SWIFT_CLASS("_TtC14BaseUIElements19AutoHeightTableView")
@interface AutoHeightTableView : UITableView
- (nonnull instancetype)initWithFrame:(CGRect)frame style:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)reloadData;
- (void)endUpdates;
- (void)performBatchUpdates:(void (^ _Nullable)(void))updates completion:(void (^ _Nullable)(BOOL))completion;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
@end

@class UIImage;

SWIFT_CLASS("_TtC14BaseUIElements20AutosizedUIImageView")
@interface AutosizedUIImageView : UIImageView
@property (nonatomic, strong) UIImage * _Nullable image;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;

SWIFT_CLASS("_TtC14BaseUIElements20ButtonWithRightImage")
@interface ButtonWithRightImage : UIButton
- (void)setTitle:(NSString * _Nullable)title forState:(UIControlState)state;
- (CGRect)imageRectForContentRect:(CGRect)contentRect SWIFT_WARN_UNUSED_RESULT;
- (CGRect)titleRectForContentRect:(CGRect)contentRect SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC14BaseUIElements17CentralButtonView")
@interface CentralButtonView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIScrollView;

SWIFT_CLASS("_TtC14BaseUIElements17DrawerViewManager")
@interface DrawerViewManager : NSObject <UIScrollViewDelegate>
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillBeginDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements23DynamicDequeueContainer")
@interface DynamicDequeueContainer : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements12GradientView")
@interface GradientView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end

@class UIColor;

SWIFT_CLASS("_TtC14BaseUIElements9LinedView")
@interface LinedView : UIView
@property (nonatomic, strong) UIColor * _Nonnull lineColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements28HorizontalSelectorScrollView")
@interface HorizontalSelectorScrollView : LinedView
@property (nonatomic, strong) UIColor * _Nonnull mColorSelector;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP14BaseUIElements22PagingableViewProtocol_")
@protocol PagingableViewProtocol <NSObject>
- (void)setClass:(SWIFT_METATYPE(UIView) _Nonnull)elementClass forConfigureElement:(void (^ _Nonnull)(NSInteger, UIView * _Nonnull))block;
- (UIView * _Nullable)viewAtIndex:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (void)reloadElements;
@property (nonatomic, copy) void (^ _Nullable selectedIndexOffsetChangeBlock)(CGFloat, BOOL);
@property (nonatomic, copy) void (^ _Nullable selectedIndexChangeBlock)(NSInteger, BOOL);
@property (nonatomic, copy) void (^ _Nullable transitionEndBlock)(BOOL);
@property (nonatomic, copy) void (^ _Nullable transitionStartBlock)(BOOL);
@property (nonatomic, readonly) NSInteger mSelectedIndex;
- (void)setSelectionIndexWithIndex:(NSInteger)index;
@property (nonatomic) NSInteger mNumberOfPages;
@end


@interface HorizontalSelectorScrollView (SWIFT_EXTENSION(BaseUIElements)) <PagingableViewProtocol>
- (void)setClass:(SWIFT_METATYPE(UIView) _Nonnull)elementClass forConfigureElement:(void (^ _Nonnull)(NSInteger, UIView * _Nonnull))block;
- (UIView * _Nullable)viewAtIndex:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (void)reloadElements;
@property (nonatomic, copy) void (^ _Nullable selectedIndexOffsetChangeBlock)(CGFloat, BOOL);
@property (nonatomic, copy) void (^ _Nullable selectedIndexChangeBlock)(NSInteger, BOOL);
@property (nonatomic, copy) void (^ _Nullable transitionEndBlock)(BOOL);
@property (nonatomic, copy) void (^ _Nullable transitionStartBlock)(BOOL);
@property (nonatomic, readonly) NSInteger mSelectedIndex;
- (void)setSelectionIndexWithIndex:(NSInteger)index;
@property (nonatomic) NSInteger mNumberOfPages;
@end


SWIFT_PROTOCOL("_TtP14BaseUIElements30HorizontalSelectorViewDelegate_")
@protocol HorizontalSelectorViewDelegate <NSObject>
- (BOOL)horizontalSelectorViewWithIsNavigationToIndexPossible:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (void)horizontalSelectorViewWithConfigure:(UIView * _Nonnull)view for:(NSInteger)index;
@optional
- (void)horizontalSelectorViewWithWillTransitionToIndex:(NSInteger)index;
- (void)horizontalSelectorViewWithDidTransitionToIndex:(NSInteger)index;
@end


SWIFT_CLASS("_TtC14BaseUIElements26ImageViewActivityIndicated")
@interface ImageViewActivityIndicated : UIImageView
- (void)addSubview:(UIView * _Nonnull)view;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements21LeftAlignedGridViewM2")
@interface LeftAlignedGridViewM2 : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
@end




SWIFT_PROTOCOL("_TtP14BaseUIElements27PagerEvadeAnimationProtocol_")
@protocol PagerEvadeAnimationProtocol <NSObject>
/// This is for making views crop, fade, jump or whatever needed to when animated in pager with <em>PagerImmersiveAnimationRunner</em>
/// \param state from 0.0 to 1.0
///
- (void)setEvadingAnimationStateWithState:(CGFloat)state;
@property (nonatomic) BOOL isCuttingFromLeft;
@property (nonatomic) CGFloat parallaxStep;
@optional
- (void)setSubEvadingAnimationStateWithState:(CGFloat)state;
@property (nonatomic, readonly, strong) UIView * _Nonnull viewForDismissialTransform;
@end


SWIFT_CLASS("_TtC14BaseUIElements10PagingView")
@interface PagingView : LinedView <PagingableViewProtocol, UIScrollViewDelegate>
@property (nonatomic, copy) void (^ _Nullable selectedIndexOffsetChangeBlock)(CGFloat, BOOL);
@property (nonatomic, copy) void (^ _Nullable selectedIndexChangeBlock)(NSInteger, BOOL);
@property (nonatomic) NSInteger mSelectedIndex;
@property (nonatomic) NSInteger mNumberOfPages;
@property (nonatomic, copy) void (^ _Nullable transitionEndBlock)(BOOL);
@property (nonatomic, copy) void (^ _Nullable transitionStartBlock)(BOOL);
- (void)reloadElements;
- (UIView * _Nullable)viewAtIndex:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (void)layoutSubviews;
- (void)setClass:(SWIFT_METATYPE(UIView) _Nonnull)elementClass forConfigureElement:(void (^ _Nonnull)(NSInteger, UIView * _Nonnull))block;
- (void)setSelectionIndexWithIndex:(NSInteger)index;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC14BaseUIElements12PickerButton")
@interface PickerButton : UIButton
@property (nonatomic, strong) UIView * _Nonnull inputView;
@property (nonatomic, strong) UIView * _Nonnull inputAccessoryView;
@property (nonatomic, readonly) BOOL canBecomeFirstResponder;
- (void)doneTapped;
- (void)cancelTapped;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements16RawImageAnimator")
@interface RawImageAnimator : UIImageView
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements17RotatingImageView")
@interface RotatingImageView : UIImageView
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements12SVGImageView")
@interface SVGImageView : UIView
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class WKWebView;
@class WKNavigationAction;
@class WKNavigation;

@interface SVGImageView (SWIFT_EXTENSION(BaseUIElements)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
@end



@class UIContextMenuInteraction;
@class UIContextMenuConfiguration;
@protocol UIContextMenuInteractionCommitAnimating;

SWIFT_CLASS("_TtC14BaseUIElements45UIContextMenuInteractionHandlerIdentifiedBase") SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface UIContextMenuInteractionHandlerIdentifiedBase : NSObject <UIContextMenuInteractionDelegate>
- (UIContextMenuConfiguration * _Nullable)contextMenuInteraction:(UIContextMenuInteraction * _Nonnull)interaction configurationForMenuAtLocation:(CGPoint)location SWIFT_WARN_UNUSED_RESULT;
- (void)contextMenuInteraction:(UIContextMenuInteraction * _Nonnull)interaction willPerformPreviewActionForMenuWithConfiguration:(UIContextMenuConfiguration * _Nonnull)configuration animator:(id <UIContextMenuInteractionCommitAnimating> _Nonnull)animator;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements53UIContextMenuInteractionHandlerIdentifiedWithDelegate") SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface UIContextMenuInteractionHandlerIdentifiedWithDelegate : UIContextMenuInteractionHandlerIdentifiedBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements34UIContextMenuInteractionIdentified") SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface UIContextMenuInteractionIdentified : UIContextMenuInteraction
- (nonnull instancetype)initWithDelegate:(id <UIContextMenuInteractionDelegate> _Nonnull)delegate SWIFT_UNAVAILABLE;
@end




@interface UIGestureRecognizer (SWIFT_EXTENSION(BaseUIElements))
- (void)handleGestureActionWithSender:(UIGestureRecognizer * _Nonnull)sender;
@end


SWIFT_CLASS("_TtC14BaseUIElements17UILabelWithOffset")
@interface UILabelWithOffset : UILabel
- (void)drawTextInRect:(CGRect)rect;
- (CGRect)textRectForBounds:(CGRect)bounds limitedToNumberOfLines:(NSInteger)numberOfLines SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements24UIScrollViewSynchronizer")
@interface UIScrollViewSynchronizer : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIScrollViewSynchronizer (SWIFT_EXTENSION(BaseUIElements)) <UIScrollViewDelegate>
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
@end






SWIFT_CLASS("_TtC14BaseUIElements52xUIContextMenuInteractionHandlerIdentifiedWithBlocks") SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface xUIContextMenuInteractionHandlerIdentifiedWithBlocks : UIContextMenuInteractionHandlerIdentifiedBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
#ifndef BASEUIELEMENTS_SWIFT_H
#define BASEUIELEMENTS_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BaseUIElements",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSCoder;

SWIFT_CLASS("_TtC14BaseUIElements17AlphaGradientView")
@interface AlphaGradientView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end

@class NSNumber;

SWIFT_CLASS("_TtC14BaseUIElements19AutoHeightTableView")
@interface AutoHeightTableView : UITableView
- (nonnull instancetype)initWithFrame:(CGRect)frame style:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)reloadData;
- (void)endUpdates;
- (void)performBatchUpdates:(void (^ _Nullable)(void))updates completion:(void (^ _Nullable)(BOOL))completion;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
@end

@class UIImage;

SWIFT_CLASS("_TtC14BaseUIElements20AutosizedUIImageView")
@interface AutosizedUIImageView : UIImageView
@property (nonatomic, strong) UIImage * _Nullable image;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;

SWIFT_CLASS("_TtC14BaseUIElements20ButtonWithRightImage")
@interface ButtonWithRightImage : UIButton
- (void)setTitle:(NSString * _Nullable)title forState:(UIControlState)state;
- (CGRect)imageRectForContentRect:(CGRect)contentRect SWIFT_WARN_UNUSED_RESULT;
- (CGRect)titleRectForContentRect:(CGRect)contentRect SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC14BaseUIElements17CentralButtonView")
@interface CentralButtonView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIScrollView;

SWIFT_CLASS("_TtC14BaseUIElements17DrawerViewManager")
@interface DrawerViewManager : NSObject <UIScrollViewDelegate>
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillBeginDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements23DynamicDequeueContainer")
@interface DynamicDequeueContainer : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements12GradientView")
@interface GradientView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end

@class UIColor;

SWIFT_CLASS("_TtC14BaseUIElements9LinedView")
@interface LinedView : UIView
@property (nonatomic, strong) UIColor * _Nonnull lineColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements28HorizontalSelectorScrollView")
@interface HorizontalSelectorScrollView : LinedView
@property (nonatomic, strong) UIColor * _Nonnull mColorSelector;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP14BaseUIElements22PagingableViewProtocol_")
@protocol PagingableViewProtocol <NSObject>
- (void)setClass:(SWIFT_METATYPE(UIView) _Nonnull)elementClass forConfigureElement:(void (^ _Nonnull)(NSInteger, UIView * _Nonnull))block;
- (UIView * _Nullable)viewAtIndex:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (void)reloadElements;
@property (nonatomic, copy) void (^ _Nullable selectedIndexOffsetChangeBlock)(CGFloat, BOOL);
@property (nonatomic, copy) void (^ _Nullable selectedIndexChangeBlock)(NSInteger, BOOL);
@property (nonatomic, copy) void (^ _Nullable transitionEndBlock)(BOOL);
@property (nonatomic, copy) void (^ _Nullable transitionStartBlock)(BOOL);
@property (nonatomic, readonly) NSInteger mSelectedIndex;
- (void)setSelectionIndexWithIndex:(NSInteger)index;
@property (nonatomic) NSInteger mNumberOfPages;
@end


@interface HorizontalSelectorScrollView (SWIFT_EXTENSION(BaseUIElements)) <PagingableViewProtocol>
- (void)setClass:(SWIFT_METATYPE(UIView) _Nonnull)elementClass forConfigureElement:(void (^ _Nonnull)(NSInteger, UIView * _Nonnull))block;
- (UIView * _Nullable)viewAtIndex:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (void)reloadElements;
@property (nonatomic, copy) void (^ _Nullable selectedIndexOffsetChangeBlock)(CGFloat, BOOL);
@property (nonatomic, copy) void (^ _Nullable selectedIndexChangeBlock)(NSInteger, BOOL);
@property (nonatomic, copy) void (^ _Nullable transitionEndBlock)(BOOL);
@property (nonatomic, copy) void (^ _Nullable transitionStartBlock)(BOOL);
@property (nonatomic, readonly) NSInteger mSelectedIndex;
- (void)setSelectionIndexWithIndex:(NSInteger)index;
@property (nonatomic) NSInteger mNumberOfPages;
@end


SWIFT_PROTOCOL("_TtP14BaseUIElements30HorizontalSelectorViewDelegate_")
@protocol HorizontalSelectorViewDelegate <NSObject>
- (BOOL)horizontalSelectorViewWithIsNavigationToIndexPossible:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (void)horizontalSelectorViewWithConfigure:(UIView * _Nonnull)view for:(NSInteger)index;
@optional
- (void)horizontalSelectorViewWithWillTransitionToIndex:(NSInteger)index;
- (void)horizontalSelectorViewWithDidTransitionToIndex:(NSInteger)index;
@end


SWIFT_CLASS("_TtC14BaseUIElements26ImageViewActivityIndicated")
@interface ImageViewActivityIndicated : UIImageView
- (void)addSubview:(UIView * _Nonnull)view;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements21LeftAlignedGridViewM2")
@interface LeftAlignedGridViewM2 : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
@end




SWIFT_PROTOCOL("_TtP14BaseUIElements27PagerEvadeAnimationProtocol_")
@protocol PagerEvadeAnimationProtocol <NSObject>
/// This is for making views crop, fade, jump or whatever needed to when animated in pager with <em>PagerImmersiveAnimationRunner</em>
/// \param state from 0.0 to 1.0
///
- (void)setEvadingAnimationStateWithState:(CGFloat)state;
@property (nonatomic) BOOL isCuttingFromLeft;
@property (nonatomic) CGFloat parallaxStep;
@optional
- (void)setSubEvadingAnimationStateWithState:(CGFloat)state;
@property (nonatomic, readonly, strong) UIView * _Nonnull viewForDismissialTransform;
@end


SWIFT_CLASS("_TtC14BaseUIElements10PagingView")
@interface PagingView : LinedView <PagingableViewProtocol, UIScrollViewDelegate>
@property (nonatomic, copy) void (^ _Nullable selectedIndexOffsetChangeBlock)(CGFloat, BOOL);
@property (nonatomic, copy) void (^ _Nullable selectedIndexChangeBlock)(NSInteger, BOOL);
@property (nonatomic) NSInteger mSelectedIndex;
@property (nonatomic) NSInteger mNumberOfPages;
@property (nonatomic, copy) void (^ _Nullable transitionEndBlock)(BOOL);
@property (nonatomic, copy) void (^ _Nullable transitionStartBlock)(BOOL);
- (void)reloadElements;
- (UIView * _Nullable)viewAtIndex:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (void)layoutSubviews;
- (void)setClass:(SWIFT_METATYPE(UIView) _Nonnull)elementClass forConfigureElement:(void (^ _Nonnull)(NSInteger, UIView * _Nonnull))block;
- (void)setSelectionIndexWithIndex:(NSInteger)index;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC14BaseUIElements12PickerButton")
@interface PickerButton : UIButton
@property (nonatomic, strong) UIView * _Nonnull inputView;
@property (nonatomic, strong) UIView * _Nonnull inputAccessoryView;
@property (nonatomic, readonly) BOOL canBecomeFirstResponder;
- (void)doneTapped;
- (void)cancelTapped;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements16RawImageAnimator")
@interface RawImageAnimator : UIImageView
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements17RotatingImageView")
@interface RotatingImageView : UIImageView
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements12SVGImageView")
@interface SVGImageView : UIView
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class WKWebView;
@class WKNavigationAction;
@class WKNavigation;

@interface SVGImageView (SWIFT_EXTENSION(BaseUIElements)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
@end



@class UIContextMenuInteraction;
@class UIContextMenuConfiguration;
@protocol UIContextMenuInteractionCommitAnimating;

SWIFT_CLASS("_TtC14BaseUIElements45UIContextMenuInteractionHandlerIdentifiedBase") SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface UIContextMenuInteractionHandlerIdentifiedBase : NSObject <UIContextMenuInteractionDelegate>
- (UIContextMenuConfiguration * _Nullable)contextMenuInteraction:(UIContextMenuInteraction * _Nonnull)interaction configurationForMenuAtLocation:(CGPoint)location SWIFT_WARN_UNUSED_RESULT;
- (void)contextMenuInteraction:(UIContextMenuInteraction * _Nonnull)interaction willPerformPreviewActionForMenuWithConfiguration:(UIContextMenuConfiguration * _Nonnull)configuration animator:(id <UIContextMenuInteractionCommitAnimating> _Nonnull)animator;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements53UIContextMenuInteractionHandlerIdentifiedWithDelegate") SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface UIContextMenuInteractionHandlerIdentifiedWithDelegate : UIContextMenuInteractionHandlerIdentifiedBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements34UIContextMenuInteractionIdentified") SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface UIContextMenuInteractionIdentified : UIContextMenuInteraction
- (nonnull instancetype)initWithDelegate:(id <UIContextMenuInteractionDelegate> _Nonnull)delegate SWIFT_UNAVAILABLE;
@end




@interface UIGestureRecognizer (SWIFT_EXTENSION(BaseUIElements))
- (void)handleGestureActionWithSender:(UIGestureRecognizer * _Nonnull)sender;
@end


SWIFT_CLASS("_TtC14BaseUIElements17UILabelWithOffset")
@interface UILabelWithOffset : UILabel
- (void)drawTextInRect:(CGRect)rect;
- (CGRect)textRectForBounds:(CGRect)bounds limitedToNumberOfLines:(NSInteger)numberOfLines SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14BaseUIElements24UIScrollViewSynchronizer")
@interface UIScrollViewSynchronizer : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIScrollViewSynchronizer (SWIFT_EXTENSION(BaseUIElements)) <UIScrollViewDelegate>
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
@end






SWIFT_CLASS("_TtC14BaseUIElements52xUIContextMenuInteractionHandlerIdentifiedWithBlocks") SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface xUIContextMenuInteractionHandlerIdentifiedWithBlocks : UIContextMenuInteractionHandlerIdentifiedBase
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
